create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
create table department(ID integer, name varchar(50));
create table class(ID integer, classname varchar(20), depId integer);
